import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCustomerForgottenPasswordTable1761049045191 implements MigrationInterface {
    name = 'CreateCustomerForgottenPasswordTable1761049045191'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_customer_user_invite_invited_by_admin"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_customer_user_invite_invited_by"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_customer_user_invite_customer_role"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_customer_user_invite_customer_location"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_customer_user_invite_customer"`);
        await queryRunner.query(`ALTER TABLE "customer_note" DROP CONSTRAINT "FK_customer_note_wo"`);
        await queryRunner.query(`ALTER TABLE "customer_note" DROP CONSTRAINT "FK_customer_note_sender"`);
        await queryRunner.query(`ALTER TABLE "customer_note" DROP CONSTRAINT "FK_customer_note_customer_sender"`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP CONSTRAINT "FK_customer_user_customer_location"`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP CONSTRAINT "FK_customer_user_customer"`);
        await queryRunner.query(`ALTER TABLE "wo" DROP CONSTRAINT "FK_wo_requested_customer_user"`);
        await queryRunner.query(`ALTER TABLE "wo" DROP CONSTRAINT "FK_wo_customer_location"`);
        await queryRunner.query(`ALTER TABLE "customer_notification" DROP CONSTRAINT "FK_customer_notification_customer_location"`);
        await queryRunner.query(`ALTER TABLE "customer_location" DROP CONSTRAINT "FK_customer_location_customer"`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" DROP CONSTRAINT "FK_customer_role_customer_users_customer_user_customer_user"`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" DROP CONSTRAINT "FK_customer_role_customer_users_customer_user_customer_role"`);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" DROP CONSTRAINT "FK_customer_location_customer_users_customer_user_customer_user"`);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" DROP CONSTRAINT "FK_customer_location_customer_users_customer_user_customer_loca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_role_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_invite_accepted"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_invite_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_invite_customer_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_invite_customer_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_invite_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_invite_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_note_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_note_customer_sender_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_note_sender_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_note_sender_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_note_wo_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_customer_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_user_is_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_167b3b7fb709d94b9ec61869e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b35e0eba429467615af186db4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31a666c5354ae395aafa2a262a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_768f93a0ea8a57a23636eae4eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e054f9932922055385bfa76b3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wo_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wo_customer_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wo_priority_level"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wo_requested_customer_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notification_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notification_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notification_customer_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notification_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notification_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_location_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_location_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_location_phone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_report_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vendor_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_role_customer_users_customer_user_customer_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_role_customer_users_customer_user_customer_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_location_customer_users_customer_user_customer_loc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_location_customer_users_customer_user_customer_use"`);
        await queryRunner.query(`CREATE TABLE "customer_forgotten_password" ("email" character varying NOT NULL, "newPasswordToken" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3df3c5e84c64743dfb91734011a" PRIMARY KEY ("email"))`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP COLUMN "customerLocationId"`);
        await queryRunner.query(`ALTER TABLE "customer_role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_role" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_role" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_location" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_location" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_location" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_location" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_refresh_session" DROP CONSTRAINT "FK_a1d2a96150b67d6386b53559374"`);
        await queryRunner.query(`ALTER TABLE "customer_refresh_session" ALTER COLUMN "customerUserId" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b8d06c03d2d85ea0b3d9324b59" ON "wo" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_156354ac38a18555a7c3b461a0" ON "customer_notification" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_2206a456f61cd9e799f0875baf" ON "notification" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_6be2d1a5e1b8a978cc74207e38" ON "report" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a941adf73729df0547393f363" ON "vendor" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_75ed80475b6a4535c60bf312b0" ON "branch" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ab89b03a98e3da9a0e43b9a87" ON "customer_role_customer_users_customer_user" ("customerRoleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b02e606bdf267a4531849f1155" ON "customer_role_customer_users_customer_user" ("customerUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7b0768d94f0afe095ffdfbcde" ON "customer_location_customer_users_customer_user" ("customerLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d363ed2bf348fa2e7457c014e" ON "customer_location_customer_users_customer_user" ("customerUserId") `);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_8958304147790c290e5bf35d023" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_23f11748e80ee7b1c630c0d5ad2" FOREIGN KEY ("invitedById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_c0e4043db2f8e311f4633ad1b6a" FOREIGN KEY ("invitedByAdminId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_b08f2d97b23422fd12789b28440" FOREIGN KEY ("customerRoleId") REFERENCES "customer_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_a4f5a126a3eca41264b18aa240b" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_note" ADD CONSTRAINT "FK_b8a87b791622e1790c65f27b2aa" FOREIGN KEY ("woId") REFERENCES "wo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_note" ADD CONSTRAINT "FK_96bb7f8e3553e4cee27e440a4f5" FOREIGN KEY ("senderId") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_note" ADD CONSTRAINT "FK_ae789bf0b507dc2a8b04c0d7590" FOREIGN KEY ("customerSenderId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD CONSTRAINT "FK_b4e9f6d25673cec79ba9db7617a" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wo" ADD CONSTRAINT "FK_8283454946f00194f90fa3590c6" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wo" ADD CONSTRAINT "FK_1e102feecc2657750108f9c2c64" FOREIGN KEY ("requestedCustomerUserId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_notification" ADD CONSTRAINT "FK_5981dfa1d09a82b606454622e25" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_location" ADD CONSTRAINT "FK_f28bdd13533f30cb54a4112a9cc" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_refresh_session" ADD CONSTRAINT "FK_a1d2a96150b67d6386b53559374" FOREIGN KEY ("customerUserId") REFERENCES "customer_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" ADD CONSTRAINT "FK_4ab89b03a98e3da9a0e43b9a877" FOREIGN KEY ("customerRoleId") REFERENCES "customer_role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" ADD CONSTRAINT "FK_b02e606bdf267a4531849f1155b" FOREIGN KEY ("customerUserId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" ADD CONSTRAINT "FK_a7b0768d94f0afe095ffdfbcde0" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" ADD CONSTRAINT "FK_8d363ed2bf348fa2e7457c014eb" FOREIGN KEY ("customerUserId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" DROP CONSTRAINT "FK_8d363ed2bf348fa2e7457c014eb"`);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" DROP CONSTRAINT "FK_a7b0768d94f0afe095ffdfbcde0"`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" DROP CONSTRAINT "FK_b02e606bdf267a4531849f1155b"`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" DROP CONSTRAINT "FK_4ab89b03a98e3da9a0e43b9a877"`);
        await queryRunner.query(`ALTER TABLE "customer_refresh_session" DROP CONSTRAINT "FK_a1d2a96150b67d6386b53559374"`);
        await queryRunner.query(`ALTER TABLE "customer_location" DROP CONSTRAINT "FK_f28bdd13533f30cb54a4112a9cc"`);
        await queryRunner.query(`ALTER TABLE "customer_notification" DROP CONSTRAINT "FK_5981dfa1d09a82b606454622e25"`);
        await queryRunner.query(`ALTER TABLE "wo" DROP CONSTRAINT "FK_1e102feecc2657750108f9c2c64"`);
        await queryRunner.query(`ALTER TABLE "wo" DROP CONSTRAINT "FK_8283454946f00194f90fa3590c6"`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP CONSTRAINT "FK_b4e9f6d25673cec79ba9db7617a"`);
        await queryRunner.query(`ALTER TABLE "customer_note" DROP CONSTRAINT "FK_ae789bf0b507dc2a8b04c0d7590"`);
        await queryRunner.query(`ALTER TABLE "customer_note" DROP CONSTRAINT "FK_96bb7f8e3553e4cee27e440a4f5"`);
        await queryRunner.query(`ALTER TABLE "customer_note" DROP CONSTRAINT "FK_b8a87b791622e1790c65f27b2aa"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_a4f5a126a3eca41264b18aa240b"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_b08f2d97b23422fd12789b28440"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_c0e4043db2f8e311f4633ad1b6a"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_23f11748e80ee7b1c630c0d5ad2"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP CONSTRAINT "FK_8958304147790c290e5bf35d023"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d363ed2bf348fa2e7457c014e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7b0768d94f0afe095ffdfbcde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b02e606bdf267a4531849f1155"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ab89b03a98e3da9a0e43b9a87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75ed80475b6a4535c60bf312b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a941adf73729df0547393f363"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6be2d1a5e1b8a978cc74207e38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2206a456f61cd9e799f0875baf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156354ac38a18555a7c3b461a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8d06c03d2d85ea0b3d9324b59"`);
        await queryRunner.query(`ALTER TABLE "customer_refresh_session" ALTER COLUMN "customerUserId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_refresh_session" ADD CONSTRAINT "FK_a1d2a96150b67d6386b53559374" FOREIGN KEY ("customerUserId") REFERENCES "customer_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_location" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_location" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_location" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_location" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customer_role" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customer_role" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD "customerLocationId" integer`);
        await queryRunner.query(`DROP TABLE "customer_forgotten_password"`);
        await queryRunner.query(`CREATE INDEX "IDX_customer_location_customer_users_customer_user_customer_use" ON "customer_location_customer_users_customer_user" ("customerUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_location_customer_users_customer_user_customer_loc" ON "customer_location_customer_users_customer_user" ("customerLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_role_customer_users_customer_user_customer_user_id" ON "customer_role_customer_users_customer_user" ("customerUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_role_customer_users_customer_user_customer_role_id" ON "customer_role_customer_users_customer_user" ("customerRoleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_branch_company" ON "branch" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_vendor_company" ON "vendor" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_report_company" ON "report" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_company" ON "notification" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_company" ON "customer" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_location_phone" ON "customer_location" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_location_name" ON "customer_location" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_location_customer_id" ON "customer_location" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notification_type" ON "customer_notification" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notification_status" ON "customer_notification" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notification_customer_location_id" ON "customer_notification" ("customerLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notification_created_at" ON "customer_notification" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notification_company" ON "customer_notification" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_wo_requested_customer_user_id" ON "wo" ("requestedCustomerUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_wo_priority_level" ON "wo" ("priorityLevel") `);
        await queryRunner.query(`CREATE INDEX "IDX_wo_customer_location_id" ON "wo" ("customerLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_wo_company" ON "wo" ("company") `);
        await queryRunner.query(`CREATE INDEX "IDX_e054f9932922055385bfa76b3e" ON "wo" ("customerPONumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_768f93a0ea8a57a23636eae4eb" ON "wo" ("recommendations") `);
        await queryRunner.query(`CREATE INDEX "IDX_31a666c5354ae395aafa2a262a" ON "wo" ("description") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b35e0eba429467615af186db4" ON "wo" ("asset") `);
        await queryRunner.query(`CREATE INDEX "IDX_167b3b7fb709d94b9ec61869e0" ON "wo" ("servicesProvided") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_is_enabled" ON "customer_user" ("isEnabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_email" ON "customer_user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_customer_location_id" ON "customer_user" ("customerLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_customer_id" ON "customer_user" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_note_wo_id" ON "customer_note" ("woId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_note_sender_type" ON "customer_note" ("senderType") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_note_sender_id" ON "customer_note" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_note_customer_sender_id" ON "customer_note" ("customerSenderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_note_created_at" ON "customer_note" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_invite_token" ON "customer_user_invite" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_invite_email" ON "customer_user_invite" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_invite_customer_role_id" ON "customer_user_invite" ("customerRoleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_invite_customer_location_id" ON "customer_user_invite" ("customerLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_invite_customer_id" ON "customer_user_invite" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_user_invite_accepted" ON "customer_user_invite" ("accepted") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_role_name" ON "customer_role" ("name") `);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" ADD CONSTRAINT "FK_customer_location_customer_users_customer_user_customer_loca" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "customer_location_customer_users_customer_user" ADD CONSTRAINT "FK_customer_location_customer_users_customer_user_customer_user" FOREIGN KEY ("customerUserId") REFERENCES "customer_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" ADD CONSTRAINT "FK_customer_role_customer_users_customer_user_customer_role" FOREIGN KEY ("customerRoleId") REFERENCES "customer_role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "customer_role_customer_users_customer_user" ADD CONSTRAINT "FK_customer_role_customer_users_customer_user_customer_user" FOREIGN KEY ("customerUserId") REFERENCES "customer_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "customer_location" ADD CONSTRAINT "FK_customer_location_customer" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_notification" ADD CONSTRAINT "FK_customer_notification_customer_location" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wo" ADD CONSTRAINT "FK_wo_customer_location" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wo" ADD CONSTRAINT "FK_wo_requested_customer_user" FOREIGN KEY ("requestedCustomerUserId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD CONSTRAINT "FK_customer_user_customer" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user" ADD CONSTRAINT "FK_customer_user_customer_location" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_note" ADD CONSTRAINT "FK_customer_note_customer_sender" FOREIGN KEY ("customerSenderId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_note" ADD CONSTRAINT "FK_customer_note_sender" FOREIGN KEY ("senderId") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_note" ADD CONSTRAINT "FK_customer_note_wo" FOREIGN KEY ("woId") REFERENCES "wo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_customer_user_invite_customer" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_customer_user_invite_customer_location" FOREIGN KEY ("customerLocationId") REFERENCES "customer_location"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_customer_user_invite_customer_role" FOREIGN KEY ("customerRoleId") REFERENCES "customer_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_customer_user_invite_invited_by" FOREIGN KEY ("invitedById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_user_invite" ADD CONSTRAINT "FK_customer_user_invite_invited_by_admin" FOREIGN KEY ("invitedByAdminId") REFERENCES "customer_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
